[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "sequelize", "pg", "node-fetch"]
  included_files = ["src/app.js", "src/config/**", "src/models/**", "src/utils/database.js"]

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "no-cache"
